export const storeBooks = [
  {
    id: 1,
    title: "The Lord of the Rings",
    img: "img/book-1.jpg",
    price: 10,
    author: "J. R. R. Tolkien",
    info: "The Lord of the Rings is an epic high-fantasy novel by English author and scholar J. R. R. Tolkien. Set in Middle-earth, a place like Earth at some distant time in the past, the story began as a sequel to Tolkien's 1937 children's book The Hobbit, but eventually developed into a much larger work. Written in stages between 1937 and 1949, The Lord of the Rings is one of the best-selling books ever written, with over 150 million copies sold.",
    inCart: false,
    inStock: 5,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: "Don Quixote",
    img: "img/book-2.jpg",
    price: 16,
    author: "Miguel de Cervantes",
    info: "The plot revolves around the adventures of a noble (hidalgo) from La Mancha named Alonso Quixano, who reads so many chivalric romances that he loses his mind and decides to become a knight-errant (caballero andante) to revive chivalry and serve his nation, under the name Don Quixote de la Mancha. He recruits a simple farmer, Sancho Panza, as his squire, who often employs a unique, earthy wit in dealing with Don Quixote's rhetorical monologues on knighthood, already considered old-fashioned at the time. Don Quixote, in the first part of the book, does not see the world for what it is and prefers to imagine that he is living out a knightly story.",
    inCart: false,
    inStock: 3,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: "A Tale of Two Cities",
    img: "img/book-3.jpg",
    price: 8,
    author: "Charles Dickens",
    info: "A Tale of Two Cities is an 1859 historical novel by Charles Dickens, set in London and Paris before and during the French Revolution. The novel tells the story of the French Doctor Manette, his 18-year-long imprisonment in the Bastille in Paris and his release to live in London with his daughter Lucie, whom he had never met. The story is set against the conditions that led up to the French Revolution and the Reign of Terror.",
    inCart: false,
    inStock: 6,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: "The Lion, the Witch and the Wardrobe",
    img: "img/book-4.jpg",
    price: 18,
    author: "C. S. Lewis",
    info: "The Lion, the Witch and the Wardrobe is a fantasy novel for children by C. S. Lewis, published by Geoffrey Bles in 1950. It is the first published and best known of seven novels in The Chronicles of Narnia (1950–1956). Most of the novel is set in Narnia, a land of talking animals and mythical creatures that is ruled by the evil White Witch. In the frame story, four English children are relocated to a large, old country house following a wartime evacuation. The youngest, Lucy, visits Narnia three times via the magic of a wardrobe in a spare room. Lucy's three siblings are with her on her third visit to Narnia. In Narnia, the siblings seem fit to fulfill an old prophecy and find themselves adventuring to save Narnia and their own lives. The lion Aslan gives his life to save one of the children; he later rises from the dead, vanquishes the White Witch, and crowns the children Kings and Queens of Narnia.",
    inCart: false,
    inStock: 8,
    count: 0,
    total: 0,
  },
];
